inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - vendor/**/*
    - db/migrate/**/*
    - db/schema.rb

plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

# --- Project conventions ---

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Layout/LineLength:
  Max: 120

# --- Aspirational metrics ---
# bin/ scripts and tests are exempt — they're inherently procedural.

Metrics/MethodLength:
  Max: 15
  Exclude:
    - bin/*
    - test/**/*

Metrics/AbcSize:
  Max: 25
  Exclude:
    - bin/*
    - test/**/*

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - bin/*
    - test/**/*

Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - bin/*
    - test/**/*

Metrics/BlockLength:
  Exclude:
    - bin/*
    - test/**/*

Metrics/ClassLength:
  Max: 125
  Exclude:
    - test/**/*

Metrics/ModuleLength:
  Max: 100

Minitest/MultipleAssertions:
  Max: 12

# --- Rails cops ---

# BuildValidator is a CLI build tool that intentionally uses puts
Rails/Output:
  Exclude:
    - lib/familyrecipes/build_validator.rb
    - db/seeds.rb

# Plain Minitest tests (Minitest::Test) don't have assert_not_* methods
Rails/RefuteMethods:
  Exclude:
    - test/cross_reference_test.rb
    - test/inflector_test.rb
    - test/nutrition_calculator_test.rb
    - test/quantity_test.rb
    - test/recipe_test.rb
    - test/scalable_number_preprocessor_test.rb
    - test/vulgar_fractions_test.rb
