default: &default
  site_title: Family Recipes
  homepage_heading: Our Recipes
  homepage_subtitle: "A collection of our family\u2019s favorite recipes."
  multi_kitchen: false

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
