# frozen_string_literal: true

# Abstract base for all models on the primary database. The cable database
# (Solid Cable) has its own base class generated by solid_cable.
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end
